### ISSUE TITLE
Website spelling mistake

### ISSUE THREAD

**Issue by schmurda** [LizardByte/awesome-sunshine#7]
### Describe the Bug

The card on LizardByte's website says 'scipts' instead of 'scripts'

![image](https://github.com/user-attachments/assets/2399e442-8b3f-42ee-bca7-e946003639e6)

### Expected Behavior

```suggestion
A collection of awesome Sunshine scripts, tools, guides and companion software.
```

### Additional Context

Not sure if 'scipts' is something specific to sunshine but thought it was spelled incorrectly.

**Comment by schmurda** [comment]
Super minor thing just thought I'd point it out

**Comment by ReenigneArcher** [comment]
Thank you for pointing that out, I would have never noticed it!

It pulls from the repo description and will be updated in a few hours.
